In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

In [3]:
my_mat =  [[1,2,3], [4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)
#step 2

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((5,5))
#tupple

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [10]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [11]:
np.linspace(0, 5, 10)# start, stop, evenly space points

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [13]:
#identity martix  - two dim square matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [14]:
#random numbers
np.random.rand(5) #one dim array

array([ 0.07478697,  0.48003976,  0.07506868,  0.17297476,  0.28532949])

In [15]:
#two dim unformly distributed from 0 to 1
np.random.rand(5,5)

array([[ 0.30407429,  0.22334154,  0.85562207,  0.29677599,  0.03151027],
       [ 0.06327228,  0.92584717,  0.0965198 ,  0.27178077,  0.13093338],
       [ 0.64030008,  0.53440175,  0.42039767,  0.60623961,  0.44569787],
       [ 0.28490491,  0.31621613,  0.27499928,  0.88821435,  0.08696161],
       [ 0.83964957,  0.85576961,  0.15401298,  0.05202418,  0.02807827]])

In [16]:
np.random.rand(5,5)

array([[ 0.84608794,  0.86334757,  0.61006863,  0.91908017,  0.676657  ],
       [ 0.96568856,  0.93876364,  0.98613421,  0.5963138 ,  0.82389683],
       [ 0.68547725,  0.05801436,  0.77466997,  0.65467375,  0.77070409],
       [ 0.04609396,  0.95956612,  0.77998577,  0.40664575,  0.33042301],
       [ 0.4326125 ,  0.90399901,  0.04353668,  0.45324337,  0.7076362 ]])

In [18]:
#standard normal distribution
np.random.randn(2)
np.random.randn(4,4)

array([[ 0.35782385,  1.2851335 ,  0.80379632, -1.43384659],
       [ 1.44874041,  0.71670728,  1.528649  , -1.39145505],
       [ 0.15764404, -0.90931747, -0.94433459,  2.68691203],
       [-1.16816784,  0.99393309,  1.58493277, -0.8995964 ]])

In [21]:
##random integer from low to high number (low, high, size)
np.random.randint(1,100,5)

array([ 7, 32, 88, 82, 80])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr=np.random.randint(0,50,10)

In [27]:
ranarr

array([49,  8, 11, 23, 26,  6, 14, 28,  3,  4])

In [28]:
##reshap takes the array and reshapes in row and column
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

49

In [30]:
ranarr.min()

3

In [32]:
##index of min value
ranarr.argmin()

8

In [33]:
#index of max value
ranarr.argmax()

0

In [38]:
#shape of a vectro
arrreshapped = arr.reshape(5,5)
arrreshapped.shape

(5, 5)

In [40]:
arrreshapped.dtype

dtype('int32')

In [41]:
myarray = np.arange(0,11)

In [42]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
myarray[8] ##get value at position 8

8

In [45]:
myarray[0:5] # position 1 to 5

array([0, 1, 2, 3, 4])

In [46]:
myarray[:8] #starting from 0 to 8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
myarray[5:] #start from 5 till end of the array

array([ 5,  6,  7,  8,  9, 10])

In [48]:
myarray[0:1]=100 ##will replace value from position 0 to 1 by 100

In [49]:
myarray

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[9:]

array([ 9, 10])

In [6]:
slice_of_array = arr[0:6] ##not a copy it's a ref
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [16]:
#copy of the array
arr_copy=arr.copy() ##this is how we copy array
arr_copy[:]=100
arr_copy
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
##2D array
arr_2d = np.array([[5,10,15], [10,20,30], [30,35,40]])
arr_2d

array([[ 5, 10, 15],
       [10, 20, 30],
       [30, 35, 40]])

In [20]:
#double bracket notation
arr_2d[0][0]

5

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [22]:
arr_2d[1][2]

30

In [23]:
#single bracket notation
arr_2d[2,1]

35

In [24]:
#sub martices top right corner
arr_2d[:2,1:]

array([[10, 15],
       [20, 30]])

In [26]:
#conditional selection
arrc = np.arange(1,11)
arrc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#boolean value using comparison
bool_array = arr>5
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [31]:
arrc[arrc>5]

array([ 6,  7,  8,  9, 10])

In [32]:
##get all element less than 3
arr[arr<3]

array([0, 1, 2])

In [35]:
arr2d = np.arange(50).reshape(5,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
arr2d[2:4, 4:6]

array([[24, 25],
       [34, 35]])

In [41]:
##Numpy Operations
## array with array
arr + arr
arr-arr
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [42]:
##array with scallars
arr+100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
##universal array functions
